version: "3"

services:
  nginx:
    build:
      context: ./frontend
      dockerfile: ../docker/frontend.dockerfile
    ports:
      - "8000:80"
    # links:
    #   - backend
#   backend:
#     build:
#       context: ./backend
#       dockerfile: ./docker/backend.dockerfile
    # volumes:
    # links:
    #   - postgres
#   postgres:
#     build:
#       context: .
#       dockerfile: ./dockerfiles/postgres.dockerfile
#     ports:
#       - "54320:5432"
#     environment:
#       POSTGRES_USER: homeadv
#       POSTGRES_PASSWORD: mD8pCKawDbZ3cZy
#       TZ: "Europe/Berlin"
