
[production.databases]
main_db = {url = "postgresql://homeadv:mD8pCKawDbZ3cZy@postgres/homeadv" }

[development.databases]
main_db = {url = "postgresql://homeadv:mD8pCKawDbZ3cZy@localhost:54320/homeadv" }

[production]
port = 80

[development]
port = 8001